"""
Latin → English lexicon for the Quaracchi critical apparatus.

Used by apparatus-translate.py to mechanically translate the highly formulaic
footnote entries in the Quaracchi Opera Omnia (1882–1902).

The apparatus is a domain-specific language:
- Manuscript sigla (A, B, C, ... Vat., cod., codd., mss.)
- Edition sigla (ed. 1, edd. 1–8, orig.)
- Formulaic verbs (habent, legunt, omittunt, addunt, restituimus, ...)
- Citation abbreviations (cap., n., lib., q., a., ad 1, ad 2, ...)
- Church father abbreviations (Aug., Thom., Alex. Hal., ...)
- Biblical book abbreviations (Rom., 1 Cor., Ps., ...)

This lexicon captures each category. Growth path: add new entries as we
encounter them in later distinctiones and volumes. When an entry is missing,
the translate script leaves it as {{untranslated}} for human/LLM review.
"""

# ============================================================================
# VERBS — the apparatus's vocabulary of textual operations
# ============================================================================
# Include both 3rd-person singular and plural (and some infinitives)
# because the apparatus uses both: "cod. B addit" and "codd. BCD addunt".

VERBS = {
    # adding / omitting
    "habent": "have",
    "habet": "has",
    "legunt": "read",
    "legit": "reads",
    "lectio": "reading",
    "omittunt": "omit",
    "omittit": "omits",
    "omisimus": "we have omitted",
    "addunt": "add",
    "addit": "adds",
    "adiungunt": "append",
    "adiungit": "appends",
    "adiciunt": "add",
    "adiicit": "adds",
    "adiiciunt": "add",
    "supplevimus": "we have supplied",
    "suppletum est": "has been supplied",
    "suppetit": "supplies",
    "suffectum est": "has been substituted",
    "substituunt": "substitute",
    "substituit": "substitutes",
    "restituimus": "we have restored",
    "restituit": "restores",
    "praetermittunt": "leave out",
    "praetermittit": "leaves out",
    "praetermisimus": "we have left out",
    "retinuimus": "we have retained",
    "expunximus": "we have struck out",
    "delent": "delete",
    "delet": "deletes",
    "delevimus": "we have deleted",
    "omisit": "omitted",
    # correcting
    "correximus": "we have corrected",
    "correxit": "corrected",
    "correctio": "correction",
    "emendavimus": "we have emended",
    "emendat": "emends",
    "immutavimus": "we have changed",
    "immutat": "changes",
    "mutat": "changes",
    "mutant": "change",
    # agreement / disagreement
    "consentit": "agrees",
    "consentiunt": "agree",
    "concordant": "agree",
    "concordat": "agrees",
    "contradicunt": "contradict",
    "contradicit": "contradicts",
    "repugnant": "are repugnant to",
    "repugnat": "is repugnant to",
    "convenit": "accords with",
    "conveniunt": "accord with",
    "postulant": "require",
    "postulat": "requires",
    # quality
    "perperam": "incorrectly",
    "recte": "correctly",
    "male": "wrongly",
    "bene": "rightly",
    # existence / location
    "desunt": "are missing",
    "deest": "is missing",
    "deerat": "was missing",
    "inveniri": "to be found",
    "invenitur": "is found",
    "inveniuntur": "are found",
    "habetur": "is found",
    "habentur": "are found",
    "respicit": "refers to",
    "respiciunt": "refer to",
    "alludunt": "allude",
    "alludit": "alludes",
    # quoting
    "citat": "cites",
    "citant": "cite",
    "affert": "adduces",
    "afferunt": "adduce",
}

# ============================================================================
# PREPOSITIONS, CONNECTIVES, AND FUNCTION WORDS
# ============================================================================

PREPOSITIONS = {
    # core prepositions
    "pro": "instead of",
    "cum": "with",
    "sine": "without",
    "contra": "against",
    "secundum": "according to",
    "sicut": "as",
    "loco": "in place of",
    "ante": "before",
    "post": "after",
    "supra": "above",
    "infra": "below",
    "ex": "from",
    "ab": "from",
    # "a" removed intentionally — single-letter preposition collides with
    # manuscript siglum A. Apparatus nearly always uses "ab" or "ex" anyway.
    "de": "concerning",
    "in": "in",
    "ad": "to",
    "per": "through",
    "inter": "between",
    "apud": "in",  # as in "apud Augustinum" = "in Augustine"
    "circa": "concerning",
    # positional phrases
    "in fine": "at the end",
    "in principio": "at the beginning",
    "in medio": "in the middle",
    "paulo ante": "a little before",
    "paulo post": "a little after",
    "immediate ante": "immediately before",
    "immediate post": "immediately after",
    "proximo loco": "in the next passage",
    "eodem loco": "in the same passage",
    "alio loco": "in another passage",
    "huius capituli": "of this chapter",
    "huius loci": "of this passage",
    "hic": "here",
    "ibi": "there",
    "ibidem": "in the same place",
    "ibid.": "ibid.",
    "eodem loco": "in the same place",
    "loc. cit.": "loc. cit.",
    "op. cit.": "op. cit.",
    # conjunctions and connectives
    "et": "and",
    "atque": "and",
    "ac": "and",
    "sed": "but",
    "vel": "or",
    "aut": "or",
    "nec": "nor",
    "neque": "nor",
    "praeter": "except",
    "excepta": "except",
    "exceptis": "except",
    "exceptus": "except",
    "nisi": "unless",
    "si": "if",
    "ut": "so that",
    "quia": "because",
    "quod": "that",
    "etiam": "also",
    "quoque": "also",
    "item": "likewise",
    "idem": "the same",
    "eadem": "the same",
    "eodem": "the same",
    "iisdem": "the same",
    "ipsum": "[the word] itself",  # common in apparatus quoting a word
    "ipsam": "[the word] itself",
    "ipso": "[the word] itself",
    "ipsa": "[the word] itself",
    # negation and modal
    "non": "not",
    "nihil": "nothing",
    "nullus": "no",
    "nulla": "no",
    "nullum": "no",
    "nullo": "no",
    "debet": "ought",
    "debent": "ought",
    "debere": "to ought",
    "potest": "can",
    "possunt": "can",
    # common adjectives in apparatus
    "omnis": "every",
    "omnes": "all",
    "omnia": "all",
    "omnibus": "all",
    "omnium": "of all",
    "omni": "every",
    "omnem": "every",
    "ceteri": "the other",
    "ceterae": "the other",
    "cetera": "the other",
    "ceteras": "the other",
    "ceteros": "the other",
    "ceteris": "the other",
    "ceterorum": "of the other",
    "ceterarum": "of the other",
    "alius": "another",
    "alia": "another",
    "alii": "others",
    "aliae": "others",
    "aliqua": "some",
    "aliquid": "something",
    "quidam": "a certain",
    "quaedam": "a certain",
    "vetustus": "old",
    "vetustior": "older",
    "vetustissimus": "oldest",
    "vetustissimis": "oldest",
    "antiquus": "ancient",
    "antiquior": "older",
    "antiquissimus": "most ancient",
    "novus": "new",
    "novior": "newer",
    "plures": "several",
    "plurimum": "mostly",
    "plerique": "most",
    "multi": "many",
    "multae": "many",
    "multa": "many",
    "multos": "many",
    "multas": "many",
    "multis": "many",
    "multorum": "of many",
    "multarum": "of many",
    "multum": "much",
    "nonnulli": "some",
    "nonnullae": "some",
    "nonnulla": "some",
    "nonnullis": "some",
    "nonnullos": "some",
    "nonnullas": "some",
    "quidam": "a certain",
    "quaedam": "a certain",
    "quoddam": "a certain",
    # relative pronouns that commonly survive into the apparatus
    "quibus": "which",
    "quorum": "whose",
    "quarum": "whose",
    "quem": "whom",
    "quam": "which",
    "quas": "which",
    "quos": "which",
    # demonstratives
    "huius": "of this",
    "huic": "to this",
    "hunc": "this",
    "hanc": "this",
    "hoc": "this",
    "hac": "this",
    "his": "these",
    "horum": "of these",
    "harum": "of these",
    "eius": "his",
    "eorum": "of those",
    "earum": "of those",
    # ablative absolute participles common in editorial notes
    "omissis": "(with X) omitted",
    "additis": "(with X) added",
    "mutatis": "(with X) changed",
    "correctis": "(with X) corrected",
    "restitutis": "(with X) restored",
    "suffectis": "(with X) substituted",
    "textus": "text",
    "textum": "text",
    "textu": "text",
    "textui": "text",
    "originale": "original",
    "originalis": "of the original",
    "originali": "original",
    "verbum": "the word",
    "verba": "the words",
    "verbis": "the words",
    "verborum": "of the words",
    "propositio": "proposition",
    "propositionis": "of the proposition",
    "propositionem": "proposition",
    "propositione": "proposition",
    # verbs of seeing/judging that appear in editorial comments
    "videtur": "seems",
    "videri": "to seem",
    "videntur": "seem",
    "videbatur": "seemed",
    "putat": "holds",
    "putant": "hold",
    "existimat": "judges",
    "existimant": "judge",
    # verb "to be"
    "est": "is",
    "sunt": "are",
    "erat": "was",
    "erant": "were",
    "sit": "is",
    "fuit": "was",
    "fuerunt": "were",
    # common apparatus nouns that aren't in quoted variant readings
    "capitulum": "chapter",
    "capituli": "of the chapter",
    "capitulo": "in the chapter",
    "capitulis": "in the chapters",
    "loco": "in place of",  # when not followed by a modifier
    "locum": "passage",
    "locus": "passage",
    "loci": "of the passage",
    "locis": "passages",
    "pars": "part",
    "partem": "part",
    "partis": "of the part",
    "parte": "part",
    "partibus": "parts",
}

# ============================================================================
# BIBLIOGRAPHIC & CITATION ABBREVIATIONS
# ============================================================================
# These map Latin scholarly citation abbreviations to their English equivalents.
# Some pass through unchanged (e.g., "cf." stays "cf.") but keeping them here
# makes the lexicon the single source of truth.

CITATION = {
    "cap.": "ch.",
    "capp.": "chs.",
    "capit.": "ch.",
    "c.": "ch.",
    "n.": "n.",
    "nn.": "nn.",
    "num.": "n.",
    "lib.": "bk.",
    "libr.": "bk.",
    "l.": "bk.",
    "tract.": "tract.",
    "tr.": "tract.",
    "pars": "part",
    "p.": "part",  # ambiguous with "page" — handled in context
    "part.": "part",
    "q.": "q.",
    "qu.": "q.",
    "quaest.": "q.",
    "a.": "a.",
    "art.": "a.",
    "d.": "d.",
    "dist.": "d.",
    "m.": "memb.",
    "memb.": "memb.",
    "membr.": "memb.",
    "inq.": "inq.",
    "inquis.": "inq.",
    "sect.": "sect.",
    "s.": "sect.",
    "§": "§",
    "col.": "col.",
    "v.": "v.",
    "vers.": "v.",
    "fol.": "fol.",
    "in corp.": "in the body of the article",
    "in corpore": "in the body of the article",
    "ad 1": "reply to obj. 1",
    "ad 2": "reply to obj. 2",
    "ad 3": "reply to obj. 3",
    "ad 4": "reply to obj. 4",
    "ad 5": "reply to obj. 5",
    "ad 6": "reply to obj. 6",
    "ad 7": "reply to obj. 7",
    "ad opp.": "reply to the opposing argument",
    "ad arg.": "reply to the argument",
    "cfr.": "cf.",
    "cf.": "cf.",
    "vide": "see",
    "v. supra": "see above",
    "v. infra": "see below",
    "vid. supra": "see above",
    "vid. infra": "see below",
    "vide supra": "see above",
    "vide infra": "see below",
    "e.g.": "e.g.",
    "i.e.": "i.e.",
    "scil.": "namely",
    "scilicet": "namely",
    "videlicet": "that is",
    "viz.": "namely",
}

# ============================================================================
# SOURCE SIGLA (generic — volume-specific sigla live in apparatus-sigla.json)
# ============================================================================

SOURCE_SIGLA = {
    "cod.": "cod.",
    "codd.": "codd.",
    "codex": "codex",
    "codices": "codices",
    "ms.": "ms.",
    "mss.": "mss.",
    "manuscr.": "ms.",
    "manuscripti": "mss.",
    "Vat.": "Vat.",
    "Vatican.": "Vat.",
    "ed.": "ed.",
    "edd.": "edd.",
    "editio": "edition",
    "editiones": "editions",
    "editor": "editor",
    "editores": "editors",
    "originale": "original",
    "orig.": "orig.",
    "textus": "text",
    "lectio": "reading",
    "var. lect.": "variant reading",
    "var.": "variant",
}

# ============================================================================
# CHURCH FATHERS, DOCTORS, AND OTHER AUTHORITIES
# ============================================================================
# Stable abbreviations Quaracchi uses for cross-references. The full name in
# English goes here; the site can build a clickable author index from these.

AUTHORS = {
    # Patristic
    "Aug.": "Augustine",
    "S. Aug.": "St. Augustine",
    "Augustinus": "Augustine",
    "Augustini": "Augustine",
    "Ambr.": "Ambrose",
    "S. Ambr.": "St. Ambrose",
    "Ambrosius": "Ambrose",
    "Hier.": "Jerome",
    "S. Hier.": "St. Jerome",
    "Hieronymus": "Jerome",
    "Greg.": "Gregory",
    "S. Greg.": "St. Gregory",
    "Gregorius": "Gregory",
    "Greg. M.": "Gregory the Great",
    "Greg. Nyss.": "Gregory of Nyssa",
    "Greg. Naz.": "Gregory Nazianzen",
    "Hilar.": "Hilary",
    "S. Hilar.": "St. Hilary",
    "Hilarius": "Hilary",
    "Basil.": "Basil",
    "S. Basil.": "St. Basil",
    "Basilius": "Basil",
    "Chrys.": "Chrysostom",
    "S. Chrys.": "St. John Chrysostom",
    "Chrysostomus": "Chrysostom",
    "Damasc.": "Damascene",
    "Io. Damasc.": "John Damascene",
    "Ioan. Damasc.": "John Damascene",
    "Dionys.": "Dionysius",
    "Pseudo-Dion.": "Pseudo-Dionysius",
    "Ps.-Dion.": "Pseudo-Dionysius",
    "Boeth.": "Boethius",
    "Boethius": "Boethius",
    "Anselm.": "Anselm",
    "S. Anselm.": "St. Anselm",
    "Anselmus": "Anselm",
    "Cassian.": "Cassian",
    "Isid.": "Isidore",
    "Isidorus": "Isidore",
    "Bernard.": "Bernard",
    "S. Bernard.": "St. Bernard",
    "Bernardus": "Bernard",
    # Scholastics
    "Alex. Hal.": "Alexander of Hales",
    "Alex. Halens.": "Alexander of Hales",
    "Alex. H.": "Alexander of Hales",
    "Alexander": "Alexander of Hales",
    "Alb.": "Albert",
    "Alb. M.": "Albert the Great",
    "B. Albert.": "Bl. Albert",
    "S. Albert.": "St. Albert",
    "Albertus": "Albert",
    "Albertus M.": "Albert the Great",
    "S. Thom.": "St. Thomas",
    "Thom.": "Thomas",
    "Thomas": "Thomas Aquinas",
    "Thom. Aq.": "Thomas Aquinas",
    "Bonav.": "Bonaventure",
    "S. Bonav.": "St. Bonaventure",
    "Bonaventura": "Bonaventure",
    "Scot.": "Scotus",
    "Ioh. Scot.": "John Duns Scotus",
    "Duns": "Duns Scotus",
    "Henric.": "Henry",
    "Henr. Gand.": "Henry of Ghent",
    "Richard.": "Richard of St. Victor",
    "Rich. a S. Vict.": "Richard of St. Victor",
    "Hugo": "Hugh of St. Victor",
    "Hugo a S. Vict.": "Hugh of St. Victor",
    "Petr. Lomb.": "Peter Lombard",
    "Lombardus": "Peter Lombard",
    "Magister": "the Master",  # = Peter Lombard in Sent. context
    "Magistri": "of the Master",
    "Guil. Altiss.": "William of Auxerre",
    "Gul. Altiss.": "William of Auxerre",
    "Guill.": "William",
    "Guil.": "William",
    "Praep.": "Praepositinus",
    "Halens.": "of Hales",
    "Brulifer": "Brulifer",
    "Trithem.": "Trithemius",
    "Durand.": "Durandus",
    # Ancient philosophers
    "Arist.": "Aristotle",
    "Aristot.": "Aristotle",
    "Philos.": "the Philosopher",  # = Aristotle in scholastic context
    "Plato": "Plato",
    "Averr.": "Averroes",
    "Avicenna": "Avicenna",
    "Comment.": "the Commentator",  # = Averroes
    "Porph.": "Porphyry",
    "Cicero": "Cicero",
    "Seneca": "Seneca",
    "Macrob.": "Macrobius",
}

# ============================================================================
# WORK TITLES (Latin → English)
# ============================================================================

WORKS = {
    "De Trin.": "On the Trinity",
    "De Trinitate": "On the Trinity",
    "De Trinit.": "On the Trinity",
    "De doctr. christ.": "On Christian Doctrine",
    "De doctrina christiana": "On Christian Doctrine",
    "De doctr. christiana": "On Christian Doctrine",
    "De civ. Dei": "City of God",
    "De civitate Dei": "City of God",
    "Confess.": "Confessions",
    "Confessiones": "Confessions",
    "Retract.": "Retractations",
    "Retractationes": "Retractations",
    "Enchir.": "Enchiridion",
    "Enchiridion": "Enchiridion",
    "Soliloq.": "Soliloquies",
    "De lib. arb.": "On Free Choice",
    "De libero arbitrio": "On Free Choice",
    "De Gen. ad litt.": "On Genesis Literally Interpreted",
    "De vera relig.": "On True Religion",
    "De mor. Eccl.": "On the Morals of the Catholic Church",
    "Tract. in Io.": "Tractates on John",
    "In Psal.": "Expositions on the Psalms",
    "Enarr. in Ps.": "Expositions on the Psalms",
    "Summa theol.": "Summa theologiae",
    "Summa theologiae": "Summa theologiae",
    "Summa theologica": "Summa theologiae",
    "Summa Halens.": "Summa Halensis",
    "Breviloq.": "Breviloquium",
    "Breviloquium": "Breviloquium",
    "Itinerar.": "Itinerarium",
    "Itinerarium": "Itinerarium",
    "Sent.": "Sentences",
    "Sententiarum": "Sentences",
    "In Sent.": "Commentary on the Sentences",
    "Report.": "Reportata",
    "Metaph.": "Metaphysics",
    "Metaphys.": "Metaphysics",
    "Phys.": "Physics",
    "Physic.": "Physics",
    "Ethic.": "Ethics",
    "Eth. Nic.": "Nicomachean Ethics",
    "Eth.": "Ethics",
    "De anima": "On the Soul",
    "De an.": "On the Soul",
    "De gen. et corr.": "On Generation and Corruption",
    "De caelo": "On the Heavens",
    "Poster. Analyt.": "Posterior Analytics",
    "Post. Anal.": "Posterior Analytics",
    "Anal. post.": "Posterior Analytics",
    "Topic.": "Topics",
    "De interpret.": "On Interpretation",
    "De interpr.": "On Interpretation",
    "Categ.": "Categories",
    "Polit.": "Politics",
    "Ep.": "Epistle",
    "Epist.": "Epistle",
    "Epistola": "Epistle",
    "Epistolae": "Epistles",
    "Serm.": "Sermon",
    "Sermo": "Sermon",
    "Hom.": "Homily",
    "Homil.": "Homily",
    "Homilia": "Homily",
    "Quaest.": "Questions",
    "Quaestiones": "Questions",
    "Quaest. disp.": "Disputed Questions",
    "De ver.": "On Truth",
    "De veritate": "On Truth",
    "De pot.": "On Power",
    "De potentia": "On Power",
    "De malo": "On Evil",
    "Monol.": "Monologion",
    "Monologion": "Monologion",
    "Proslog.": "Proslogion",
    "Proslogion": "Proslogion",
    "De divinis Nominibus": "On the Divine Names",
    "De div. Nom.": "On the Divine Names",
    "Coel. Hierarch.": "Celestial Hierarchy",
    "Cael. Hier.": "Celestial Hierarchy",
    "Hierarch.": "Hierarchy",
    "De fide orth.": "On the Orthodox Faith",
    "De fide orthodoxa": "On the Orthodox Faith",
    "Collect.": "Collectanea",
    "Glossa": "Gloss",
    "Glossa ord.": "Ordinary Gloss",
    "Patrol. Lat.": "Patrologia Latina",
    "PL": "PL",
    "ML": "ML",
}

# ============================================================================
# BIBLICAL BOOKS (Latin → English, using Catholic abbreviations)
# ============================================================================

BIBLE = {
    # OT
    "Gen.": "Gen.",
    "Genes.": "Gen.",
    "Exod.": "Ex.",
    "Lev.": "Lev.",
    "Num.": "Num.",
    "Deut.": "Deut.",
    "Ios.": "Josh.",
    "Iud.": "Judg.",
    "Ruth": "Ruth",
    "1 Reg.": "1 Sam.",
    "2 Reg.": "2 Sam.",
    "3 Reg.": "1 Kgs.",
    "4 Reg.": "2 Kgs.",
    "1 Par.": "1 Chr.",
    "2 Par.": "2 Chr.",
    "Esdr.": "Ezra",
    "Neh.": "Neh.",
    "Tob.": "Tob.",
    "Iudith": "Jdt.",
    "Esth.": "Esth.",
    "Iob": "Job",
    "Ps.": "Ps.",
    "Psal.": "Ps.",
    "Psalm.": "Ps.",
    "Prov.": "Prov.",
    "Eccles.": "Eccl.",
    "Eccl.": "Eccl.",
    "Eccli.": "Sir.",
    "Cant.": "Song",
    "Sap.": "Wis.",
    "Is.": "Is.",
    "Isa.": "Is.",
    "Isai.": "Is.",
    "Ier.": "Jer.",
    "Ierem.": "Jer.",
    "Thren.": "Lam.",
    "Lam.": "Lam.",
    "Bar.": "Bar.",
    "Ez.": "Ez.",
    "Ezech.": "Ez.",
    "Dan.": "Dan.",
    "Os.": "Hos.",
    "Ioel": "Joel",
    "Am.": "Am.",
    "Abd.": "Ob.",
    "Ion.": "Jon.",
    "Mich.": "Mic.",
    "Nah.": "Nah.",
    "Habac.": "Hab.",
    "Soph.": "Zeph.",
    "Agg.": "Hag.",
    "Zach.": "Zech.",
    "Mal.": "Mal.",
    "1 Mach.": "1 Macc.",
    "2 Mach.": "2 Macc.",
    # NT
    "Matth.": "Mt.",
    "Mt.": "Mt.",
    "Marc.": "Mk.",
    "Mc.": "Mk.",
    "Luc.": "Lk.",
    "Lc.": "Lk.",
    "Io.": "Jn.",
    "Ioan.": "Jn.",
    "Ioh.": "Jn.",
    "Act.": "Acts",
    "Actus": "Acts",
    "Rom.": "Rom.",
    "1 Cor.": "1 Cor.",
    "2 Cor.": "2 Cor.",
    "Gal.": "Gal.",
    "Ephes.": "Eph.",
    "Eph.": "Eph.",
    "Philipp.": "Phil.",
    "Phil.": "Phil.",
    "Col.": "Col.",
    "1 Thess.": "1 Thes.",
    "2 Thess.": "2 Thes.",
    "1 Tim.": "1 Tim.",
    "2 Tim.": "2 Tim.",
    "Tit.": "Tit.",
    "Philem.": "Phlm.",
    "Hebr.": "Heb.",
    "Heb.": "Heb.",
    "Iac.": "Jas.",
    "1 Petr.": "1 Pet.",
    "2 Petr.": "2 Pet.",
    "1 Io.": "1 Jn.",
    "2 Io.": "2 Jn.",
    "3 Io.": "3 Jn.",
    "Iud.": "Jude",
    "Apoc.": "Rev.",
}


def merged_lexicon() -> dict:
    """
    Return a single merged dict of all lexicon entries.
    Later categories override earlier ones when keys collide.
    """
    merged = {}
    for section in (
        VERBS,
        PREPOSITIONS,
        CITATION,
        SOURCE_SIGLA,
        AUTHORS,
        WORKS,
        BIBLE,
    ):
        merged.update(section)
    return merged
